config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'
  
  get     'login'   => 'sessions#new'
  post    'login'   => 'sessions#create'
  delete  'logout'  => 'sessions#destroy'
    
  resources :lists, except: [:show] do
    resources :tasks
  end
  resources :users

end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  belongs_to :user
  validates :name, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list
  validates :name, presence: true
  validates :date, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :lists, dependent: :destroy
  
  attr_accessor :remember_token
  before_save :downcase_email
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
                    
  private

    def downcase_email
      self.email.downcase!
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = 'Please log in'
      redirect_to login_path
    end
  end
  
  def not_logged_in_user
    if logged_in?
      flash[:danger] = 'Already logged in'
      redirect_to root_path
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_list, only: [:edit, :update, :destroy]
  
  def index
    @lists = current_user.lists if logged_in?
    render layout: 'lists_sidebar'
  end
  
  def new
    @list = List.new
  end
  
  def create
    @list = current_user.lists.build(list_params)
    respond_to do |format|
      if @list.save
        @lists = current_user.lists
        format.html { redirect_to root_path }
        format.js
      else
        error_block = -> { render :new  }
        format.html &error_block
        format.js &error_block
      end
    end
  end
  
  def edit
  end
  
  def update 
    if @list.update(list_params)
      redirect_to lists_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @list.destroy
    @lists = current_user.lists
  end
  
  private
  def list_params
    params.require(:list).permit(:name)
  end
  
  def find_list
    @list = List.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    respond_to do |format|
      format.html # default
      format.js # modal
    end
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      @lists = user.lists
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or root_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    flash[:success] = 'You are now logged out'
    redirect_to root_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_list, only: [:index, :new, :create]
  
  def index
    @tasks = @list.tasks.where(active: true)
  end
  
  def new
    @task = @list.tasks.build
  end
  
  def create
    @task = @list.tasks.build(task_params)
    respond_to do |format|
      if @task.save
        @tasks = @list.tasks.where(active: true)
        format.html { redirect_to root_path }
        format.js
      else
        error_block = -> { render :new  }
        format.html &error_block
        format.js &error_block
      end
    end
  end
  
  def destroy
    
  end
  
  private
  def task_params
    params.require(:task).permit(:name, :date, :active, :list_id)
  end
  
  def find_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :not_logged_in_user, only: [:new, :create]
  
  def new
    @user = User.new
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome #{@user.name} we hope you have fun"
      redirect_to root_path
    else
      render :new
    end
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_a_modal?
    !!request.xhr?
  end
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    forget current_user
    session.delete(:user_id)
    @current_user = nil
  end
  
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
  def redirect_back_or(default)
    redirect_to session[:forward_url] || default
    session.delete(:forward_url)
  end

  def store_location
    session[:forward_url] = request.url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_side_nav.html.haml
.collapse.navbar-collapse.navbar-ex1-collapse
  %ul.nav.navbar-nav.side-nav.side-scrollable
    =render 'lists/side_nav_data'

app/views/layouts/_top_nav.html.haml
.navbar-header
  %button{:type=>"button", :class=>"navbar-toggle", :data=>{:toggle=>"collapse"}, :data=>{:target=>".navbar-ex1-collapse"}}
    %span.sr-only Toggle navigation
    %span.icon-bar
    %span.icon-bar
    %span.icon-bar
  =link_to 'ToDoList', root_path, class: 'navbar-brand'

%ul.nav.navbar-right.top-nav
  =render 'users/top_nav_data'
        
<!-- navigation modal -->
#modal-window.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel2", :role => "dialog", :tabindex => "-1"}
  .modal-dialog

app/views/layouts/application.html.haml
!!!
%html
  %head
    %titleToDoList
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    #alerts
      =render 'shared/flash_messages'
    #overlay
      .spinner
        .double-bounce1
        .double-bounce2
  
    #wrapper
      %nav{:class=>"navbar navbar-inverse navbar-fixed-top", :role=>"navigation"}
        =render 'layouts/top_nav'
        -if content_for?(:sidebar)
          = yield(:sidebar)
      #page-wrapper
        = yield

app/views/layouts/lists_sidebar.html.haml
-content_for :sidebar do render 'layouts/side_nav' end
=render template: 'layouts/application'

app/views/lists/_form.html.haml
=form_for(@list, remote: is_a_modal?) do |l|
  = render 'shared/error_messages', :object => l.object
  
  =l.label :name, class: 'control-label'
  =l.text_field :name, class: 'form-control'
  
  =l.submit class: 'btn btn-primary'

app/views/lists/_list.html.haml
%li
  =link_to list.name, list_tasks_path(list), remote: true

app/views/lists/_new_box.html.haml
-content_for :box_title do
  =content_tag 'i', 'New List', class: "fa fa-list"
=render 'shared/content_box'

app/views/lists/_side_nav_data.html.haml
-if logged_in?
  %li
    =link_to new_list_path, remote: true, :'data-toggle' => 'modal',
                                       :'data-target' => '#modal-window',
                                       class: 'btn-success highlight-li' do
      %span.highlight-li
        %i.fa.fa-fw.fa-plus-circle
        New List
  =render @lists.sort { |a,b| a.name.downcase <=> b.name.downcase }

app/views/lists/create.js.haml
$(".side-nav").html("#{escape_javascript(render 'lists/side_nav_data')}");
$("#modal-window").modal('hide');

app/views/lists/destroy.js.haml
$(".side-nav").html("#{escape_javascript(render 'lists/side_nav_data')}");
$("#page-wrapper").html("#{escape_javascript(render template: 'lists/index')}");

app/views/lists/edit.html.haml
%h1 Editar la lista
=form_for(@list) do |l|
  =l.text_field :name
  =l.submit :editar, {class: "btn btn-primary btn-xs"}

app/views/lists/index.html.haml
.content-index
  -if logged_in?
    %p
      Welcome #{current_user.name}!
      %br
      Click on the list you want to add new tasks or just view the current tasks.
  -else
    %p 
      Welcome to ToDoList!
      %br
      If you already have an account
      =link_to "click here", login_path, remote: true, :'data-toggle' => 'modal', :'data-target' => '#modal-window'
      to log in!
      %br
      If you don't have an account yet
      =link_to "click here", new_user_path, remote: true, :'data-toggle' => 'modal', :'data-target' => '#modal-window'
      to sing up now!

app/views/lists/new.html.haml
= render 'shared/page', partial: 'new_box'

app/views/lists/new.js.haml
$("#modal-window .modal-dialog").html("#{escape_javascript(render 'lists/new_box')}");

app/views/shared/_content_box.html.haml
.modal-content
  .modal-header
    %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :style => "display: #{content_for?(:close_button_display) ? yield(:close_button_display) : 'block'};", :type => "button"}
      %span{"aria-hidden" => "true"} ×
    %h1#myModalLabel.modal-title.text-center
      =yield :box_title
  .modal-body
    -if content_for?(:box_body)
      =yield(:box_body)
    -else 
      =render 'form'
  .modal-footer
    =yield :box_footer

app/views/shared/_error_messages.html.haml
-if object.errors.any?
  #error_explanation
    .alert.alert-danger
      =pluralize(object.errors.count, 'error')
      prohibited the user from being created
    %ul
      - object.errors.full_messages.each do |msg|
        %li
          =msg

app/views/shared/_flash_messages.html.haml
-flash.each do |type,msg|
  =content_tag(:div, msg, class: "alert alert-#{type}")

app/views/shared/_page.html.haml
-provide(:close_button_display, 'none')
.vertical-center
  .modal-dialog
    =render partial

app/views/tasks/_form.html.haml
=form_for([@list, @task], remote: is_a_modal?) do |t|
  = render 'shared/error_messages', :object => t.object

  =t.label :name, class: 'control-label'
  =t.text_field :name, class: 'form-control'
  
  =t.label :date,  "Expiration Date", {class: 'control-label'}
  =t.text_field :date, {:class => "datepicker form-control", "readonly" => "readonly"}
  
  =t.label :active, class: "checkbox inline" do
    =t.check_box :active
    %span Active?
  
  =t.submit class: 'btn btn-primary'
  
:javascript  
  $(document).ready(function($) {  
    $('.datepicker').datepicker(
      { dateFormat: 'yy-mm-dd' }
    );
  });

app/views/tasks/_new_box.html.haml
-content_for :box_title do
  =content_tag 'i', 'New Task', class: "fa fa-tasks"
=render 'shared/content_box'

app/views/tasks/_task.html.haml
.content-task
  =link_to new_list_task_path(@list), remote: true, :'data-toggle' => 'modal',
                                       :'data-target' => '#modal-window',
                                       class: 'btn btn-success list-action' do
    %span.highlight-li
      %i.fa.fa-fw.fa-plus-circle
      New Task
  =link_to list_path(@list), remote: true, method: :delete, data: { confirm: 'Are you sure?' },
                                       class: 'btn btn-danger list-action' do
    %span.highlight-li
      %i.fa.fa-fw.fa-minus-circle
      Delete List
  .tasks
    -if @tasks.empty?
      %p The list does not have tasks
    -else
      -@tasks.each do |t|
        %form
          %fieldset
            %legend
              =t.name
            Name:
            %p
              =t.name
            Expiration date:
            %p
              =t.date

app/views/tasks/create.js.haml
$("#page-wrapper").html($("#{escape_javascript(render "task")}"));
$("#modal-window").modal('hide');

app/views/tasks/index.js.haml
$("#page-wrapper").html($("#{escape_javascript(render "task")}"));

app/views/tasks/new.html.haml
= render 'shared/page', partial: 'new_box'

app/views/tasks/new.js.haml
$("#modal-window .modal-dialog").html("#{escape_javascript(render 'tasks/new_box')}");

app/views/users/_form.html.haml
= form_for(@user, html: { class: 'form-horizontal' }) do |f|
  = render 'shared/error_messages', object: f.object

  = f.label :name, class: 'control-label'
  = f.text_field :name, class: 'form-control'

  = f.label :email, class: 'control-label'
  = f.text_field :email, class: 'form-control'

  = f.label :password, class: 'control-label'
  = f.password_field :password, class: 'form-control'

  = f.label :password_confirmation, class: 'control-label'
  = f.password_field :password_confirmation, class: 'form-control'

  = f.submit class: 'btn btn-primary'

app/views/users/_new_box.html.haml
- content_for :box_title do
  = content_tag 'i', 'Sign Up', class: 'fa fa-sign-in'

= render 'shared/content_box'

app/views/users/_top_nav_data.html.haml
-if logged_in?
  %li.dropdown
    %a{:href=>"#", :class=>"dropdown-toggle", :data=>{:toggle=>"dropdown"}}
      %i.fa.fa-user
      =current_user.name
      %b.caret
    %ul.dropdown-menu
      %li
        =link_to current_user do
          %i.fa.fa-fw.fa-user
          Profile
      %li.divider
      %li
        =link_to logout_path, method: :delete do
          %i.fa.fa-fw.fa-power-off
          Log Out
-else
  %li
    =link_to login_path, remote: true, :'data-toggle' => 'modal', :'data-target' => '#modal-window' do
      %i.fa.fa-sign-in
        Log In

app/views/users/new.html.haml
= render 'shared/page', partial: 'new_box'

app/views/users/new.js.haml
$("#modal-window .modal-dialog").html("#{escape_javascript(render 'users/new_box')}");

app/views/users/show.html.haml
=@user.name
=gravatar_for @user